"use client";
import { useEffect, useMemo, useState } from "react";
import { Chess, type Square } from "chess.js";
import { MiniChessboard } from "@/components/mini-chessboard";
import { tacticsPuzzles, type TacticsPuzzle } from "@/lib/tactics";
type Outcome = "solved" | "missed" | null;
type SavedProgress = { rating: number; solved: number; attempted: number; recent: string[] };
const STORAGE_KEY = "schach-taktik-progress-v1";
const initial: SavedProgress = { rating: 1000, solved: 0, attempted: 0, recent: [] };
function readProgress(): SavedProgress { try { const p = JSON.parse(localStorage.getItem(STORAGE_KEY) ?? "null") as Partial<SavedProgress> | null; if (!p) return initial; return { rating: Math.max(400,Math.min(2400,Number(p.rating)||1000)), solved: Math.max(0,Number(p.solved)||0), attempted: Math.max(0,Number(p.attempted)||0), recent: Array.isArray(p.recent)?p.recent.filter((id): id is string=>typeof id==="string").slice(-4):[] }; } catch { return initial; } }
function choosePuzzle(rating:number,recent:string[]):TacticsPuzzle { const nearby=tacticsPuzzles.filter(p=>Math.abs(p.rating-rating)<=350&&!recent.includes(p.id)); if(nearby.length) return nearby[Math.floor(Math.random()*nearby.length)]; const distances=tacticsPuzzles.map(p=>Math.abs(p.rating-rating)); const nearest=Math.min(...distances); const pool=tacticsPuzzles.filter(p=>Math.abs(p.rating-rating)===nearest); return pool[Math.floor(Math.random()*pool.length)]; }
export default function TacticsPage() {
 const [progress,setProgress]=useState(initial); const [puzzle,setPuzzle]=useState(tacticsPuzzles[0]); const [selected,setSelected]=useState<string|null>(null); const [outcome,setOutcome]=useState<Outcome>(null); const [message,setMessage]=useState(""); const [ready,setReady]=useState(false);
 useEffect(()=>{const saved=readProgress();setProgress(saved);setPuzzle(choosePuzzle(saved.rating,saved.recent));setReady(true);},[]);
 useEffect(()=>{if(ready)localStorage.setItem(STORAGE_KEY,JSON.stringify(progress));},[progress,ready]);
 const chess=useMemo(()=>new Chess(puzzle.fen),[puzzle]);
 const targets=useMemo(()=>{if(!selected||outcome)return[];try{return chess.moves({square:selected as Square,verbose:true}).map(m=>m.to);}catch{return[];}},[chess,selected,outcome]);
 function finish(correct:boolean){if(outcome)return;const answer=new Chess(puzzle.fen);const best=answer.move({from:puzzle.solution.slice(0,2),to:puzzle.solution.slice(2,4),promotion:puzzle.solution[4]||"q"});setProgress({rating:Math.max(400,Math.min(2400,progress.rating+(correct?12:-10))),solved:progress.solved+(correct?1:0),attempted:progress.attempted+1,recent:[...progress.recent,puzzle.id].slice(-4)});setOutcome(correct?"solved":"missed");setSelected(null);setMessage(correct?"Richtig! "+best.san+(puzzle.kind==="mate"?" setzt matt.":" gewinnt die Figur.")+" Deine Taktik-Elo steigt um 12.":"Noch nicht. Gesucht war "+best.san+". Deine Taktik-Elo sinkt um 10.");}
 function selectSquare(square:string){if(outcome)return;const position=new Chess(puzzle.fen);const piece=position.get(square as Square);if(!selected){if(piece?.color==="w")setSelected(square);return;}if(square===selected){setSelected(null);return;}if(piece?.color==="w"){setSelected(square);return;}if(!targets.includes(square as Square)){setSelected(null);return;}const move=selected+square;let mate=false;if(puzzle.kind==="mate"){try{position.move({from:selected,to:square,promotion:"q"});mate=position.isCheckmate();}catch{mate=false;}}finish(move===puzzle.solution.slice(0,4)||mate);}
 function nextPuzzle(){setPuzzle(choosePuzzle(progress.rating,progress.recent));setSelected(null);setOutcome(null);setMessage("");}
 return <main className="min-h-screen bg-slate-950 px-5 py-8 text-slate-100 sm:px-8 sm:py-10"><div className="mx-auto max-w-6xl"><header className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-emerald-400">Training</p><h1 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">Taktikaufgaben</h1><p className="mt-2 text-sm text-slate-400">Zufällige Aufgaben passend zu deiner aktuellen Taktik-Elo.</p></div><div className="rounded-xl border border-emerald-400/20 bg-emerald-400/5 px-5 py-3"><p className="text-xs font-medium uppercase tracking-wider text-slate-400">Deine Taktik-Elo</p><p className="mt-1 text-3xl font-bold tabular-nums text-emerald-300">{progress.rating}</p></div></header>
 <div className="grid items-start gap-5 lg:grid-cols-[minmax(0,1.35fr)_minmax(280px,0.65fr)]"><section className="rounded-2xl border border-slate-800 bg-slate-900/50 p-3 sm:p-5"><div className="mb-4 flex items-center justify-between gap-3 px-1"><div><p className="text-sm font-semibold text-white">{puzzle.prompt}</p><p className="mt-1 text-xs text-slate-500">Du spielst mit Weiß · {puzzle.rating} Elo</p></div><span className="shrink-0 rounded-lg border border-slate-700 px-2.5 py-1.5 text-xs text-slate-300">{puzzle.theme}</span></div><MiniChessboard fen={puzzle.fen} label="Taktikaufgabe, Weiß am Zug" onSquareClick={selectSquare} selected={selected} targets={targets}/><div aria-live="polite" className={"mt-4 min-h-12 rounded-lg px-4 py-3 text-sm "+(outcome==="solved"?"bg-emerald-400/10 text-emerald-200":outcome==="missed"?"bg-amber-400/10 text-amber-100":"bg-slate-800/70 text-slate-400")}>{message||"Wähle eine Figur und danach das Zielfeld."}</div>{outcome&&<button type="button" onClick={nextPuzzle} className="mt-3 w-full rounded-lg bg-emerald-400 px-4 py-3 text-sm font-semibold text-slate-950 transition hover:bg-emerald-300">Nächste Aufgabe →</button>}</section>
 <aside className="space-y-4"><section className="rounded-2xl border border-slate-800 bg-slate-900/50 p-5"><h2 className="font-semibold">Dein Fortschritt</h2><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-xl bg-slate-800/70 p-4"><p className="text-xs text-slate-400">Gelöst</p><p className="mt-1 text-2xl font-semibold tabular-nums">{progress.solved}</p></div><div className="rounded-xl bg-slate-800/70 p-4"><p className="text-xs text-slate-400">Versucht</p><p className="mt-1 text-2xl font-semibold tabular-nums">{progress.attempted}</p></div></div><p className="mt-4 text-xs leading-5 text-slate-500">Die Wertung wird nach jeder Aufgabe angepasst. Fortschritt wird in diesem Browser gespeichert.</p></section><section className="rounded-2xl border border-slate-800 p-5"><h2 className="font-semibold">So funktioniert’s</h2><p className="mt-2 text-sm leading-6 text-slate-400">Die Aufgaben werden zufällig ausgewählt und orientieren sich an deiner Taktik-Elo. Löse die Stellung mit einem Zug; danach erhältst du direkt Rückmeldung und die nächste Aufgabe.</p></section></aside></div></div></main>;
}
